#!/bin/bash
# Create the .env.production file and populate it with the environment variables
touch .env.production

NEXT_PUBLIC_AGIXT_SERVER="${NEXT_PUBLIC_AGIXT_SERVER:-http://localhost:7437}"
NEXT_PUBLIC_AGIXT_AGENT="${NEXT_PUBLIC_AGIXT_AGENT:-gpt4free}"
NEXT_PUBLIC_AGIXT_INSIGHT_AGENT="${NEXT_PUBLIC_AGIXT_INSIGHT_AGENT:-gpt4free}"
NEXT_PUBLIC_AGIXT_MODE="${NEXT_PUBLIC_AGIXT_MODE:-prompt}"
NEXT_PUBLIC_AGIXT_PROMPT_NAME="${NEXT_PUBLIC_AGIXT_PROMPT_NAME:-Chat}"
NEXT_PUBLIC_AGIXT_PROMPT_CATEGORY="${NEXT_PUBLIC_AGIXT_PROMPT_CATEGORY:-Default}"
NEXT_PUBLIC_AGIXT_CHAIN="${NEXT_PUBLIC_AGIXT_CHAIN:-Postgres Chat}"
NEXT_PUBLIC_AGIXT_USE_SELECTED_AGENT="${NEXT_PUBLIC_AGIXT_USE_SELECTED_AGENT:-true}"
NEXT_PUBLIC_AGIXT_CHAIN_ARGS="${NEXT_PUBLIC_AGIXT_CHAIN_ARGS:-{}}"
NEXT_PUBLIC_AGIXT_DARKMODE="${NEXT_PUBLIC_AGIXT_DARKMODE:-true}"
NEXT_PUBLIC_AGIXT_FILE_UPLOAD_ENABLED="${NEXT_PUBLIC_AGIXT_FILE_UPLOAD_ENABLED:-false}"
NEXT_PUBLIC_AGIXT_SHOW_CONVERSATION_BAR="${NEXT_PUBLIC_AGIXT_SHOW_CONVERSATION_BAR:-true}"
NEXT_PUBLIC_AGIXT_CONVERSATION_NAME="${NEXT_PUBLIC_AGIXT_CONVERSATION_NAME:-Test}"

# Write the environment variables to .env.production
cat <<EOL > .env.production
NEXT_PUBLIC_AGIXT_SERVER=$NEXT_PUBLIC_AGIXT_SERVER
NEXT_PUBLIC_AGIXT_AGENT=$NEXT_PUBLIC_AGIXT_AGENT
NEXT_PUBLIC_AGIXT_INSIGHT_AGENT=$NEXT_PUBLIC_AGIXT_INSIGHT_AGENT
NEXT_PUBLIC_AGIXT_MODE=$NEXT_PUBLIC_AGIXT_MODE
NEXT_PUBLIC_AGIXT_PROMPT_NAME=$NEXT_PUBLIC_AGIXT_PROMPT_NAME
NEXT_PUBLIC_AGIXT_PROMPT_CATEGORY=$NEXT_PUBLIC_AGIXT_PROMPT_CATEGORY
NEXT_PUBLIC_AGIXT_CHAIN=$NEXT_PUBLIC_AGIXT_CHAIN
NEXT_PUBLIC_AGIXT_USE_SELECTED_AGENT=$NEXT_PUBLIC_AGIXT_USE_SELECTED_AGENT
NEXT_PUBLIC_AGIXT_CHAIN_ARGS=$NEXT_PUBLIC_AGIXT_CHAIN_ARGS
NEXT_PUBLIC_AGIXT_DARKMODE=$NEXT_PUBLIC_AGIXT_DARKMODE
NEXT_PUBLIC_AGIXT_FILE_UPLOAD_ENABLED=$NEXT_PUBLIC_AGIXT_FILE_UPLOAD_ENABLED
NEXT_PUBLIC_AGIXT_SHOW_CONVERSATION_BAR=$NEXT_PUBLIC_AGIXT_SHOW_CONVERSATION_BAR
NEXT_PUBLIC_AGIXT_CONVERSATION_NAME=$NEXT_PUBLIC_AGIXT_CONVERSATION_NAME
EOL

npm start
