name: Build and Test

on: ['push']
jobs:
  build-baremetal:
    uses: ./.github/workflows/build-baremetal.yml
    name: Build / Baremetal
  build-docker:
    uses: ./.github/workflows/build-docker.yml
    name: Build / Docker
    with:
      registry-dockerhub-enable: false # ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      registry-repo-name: AGInteractive
      registry-readme: ./docs/README.md
      build-args: |
        AGINTERACTIVE_SERVER=http://agixt:7437
        APP_NAME=AGInteractive CICD
        APP_URI=http://aginteractive:1109
      tags: |
        type=raw,value={{branch}}-cicd
        type=semver,pattern={{raw}}-cicd,enable=${{ github.ref_type == 'tag' }}
        type=raw,value=latest-cicd,enable=${{ github.ref_type == 'tag' }}
        type=sha
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  # test-ui:
  #   needs: build
  #   uses: ./.github/workflows/test.yml
  #   name: Basic UI
  #   permissions:
  #     contents: read
  #     packages: read
  #   with:
  #     notebook: tests/FrontEnd.ipynb
  #     front-end-image: ${{ needs.build.outputs.primary-image }}
  #     report-name: 'interactive-tests'
  #   secrets:
  #     GHCR_PAT: ${{ secrets.GHCR_PAT }}
  #     DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  #     EZLOCALAI_URI: ${{ secrets.EZLOCALAI_URI }}
  #     EZLOCALAI_API_KEY: ${{ secrets.EZLOCALAI_API_KEY }}
  #     DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
